jobs:
  add-to-project:
    name: Add Dependency Upgrade PR to project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/add-to-project@main
      with:
        github-token: ${{ secrets.ADD_PROJECT_TOKEN }}
        labeled: 'Type: Dependency Upgrade'
        project-url: https://github.com/orgs/AxonFramework/projects/2
name: Axon Framework
on:
  repository_dispatch:
    types: trigger-ga___add-to-project.yml
