env:
  VALE_VERSION: ${{ vars.LIBRARY_VALE_VERSION || '3.3.0' }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - continue-on-error: true
      name: Install vale
      run: 'wget "https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz"

        sudo tar -xvzf vale_${VALE_VERSION}_Linux_64-bit.tar.gz -C /usr/local/bin
        vale

        '
    - continue-on-error: true
      name: Generate Site
      run: 'cd docs/_playbook/

        npm install

        export GIT_CREDENTIALS=''https://axoniq-devops:${{ secrets.LIBRARY_DEVBOT_TOKEN
        }}@github.com''

        echo ''Using'' `vale -v`

        npx antora playbook.yaml

        '
    - continue-on-error: true
      if: ${{ github.event_name == 'push'}}
      name: Notify AxonIQ Library (if a push to a tracked branch)
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.LIBRARY_DEVBOT_TOKEN }}
        script: "await github.rest.actions.createWorkflowDispatch({\n  owner: 'AxonIQ',\n\
          \  repo: 'axoniq-library-site',\n  workflow_id: 'publish.yml',\n  ref: 'main'\n\
          })"
name: Trigger documentation build
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
