jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java-version }}
        server-id: sonatype
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      if: ${{ !matrix.sonar-enabled }}
      name: Regular Build
      run: './mvnw -B -U -Dstyle.color=always -Possrh -Pintegration-test -Djacoco.skip=true
        clean verify

        '
    - continue-on-error: true
      if: matrix.sonar-enabled
      name: Build with Coverage reports
      run: './mvnw -B -U -Dstyle.color=always -Possrh -Dcoverage clean verify

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ success() && matrix.sonar-enabled && github.event.pull_request.head.repo.full_name
        == github.repository }}
      name: Sonar Analysis
      run: './mvnw -B -Dstyle.color=always sonar:sonar \

        -Dsonar.projectKey=AxonFramework_AxonFramework \

        -Dsonar.organization=axonframework \

        -Dsonar.host.url=https://sonarcloud.io \

        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

        '
    - continue-on-error: true
      if: always()
      name: Create test summary
      uses: test-summary/action@v2
      with:
        paths: '**/target/surefire-reports/TEST-*.xml'
        show: fail, skip
    strategy:
      fail-fast: false
      matrix:
        include:
        - java-version: 8
          sonar-enabled: false
        - java-version: 11
          sonar-enabled: false
        - java-version: 17
          sonar-enabled: true
        - java-version: 21
          sonar-enabled: false
name: Axon Framework
on:
  repository_dispatch:
    types: trigger-ga___pullrequest.yml
