jobs:
  my-job:
    name: Slack notification
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      id: slack
      name: Send release notification data to Slack workflow
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: "{\n  \"release-name\": \"${{ github.event.release.name }}\",\n \
          \ \"release-url\" : \"${{ github.event.release.html_url }}\"\n}\n"
name: Announce release on Slack
on:
  repository_dispatch:
    types: trigger-ga___slack-release-notification.yml
